OrdererOrgs:
    - Name: Orderer
      Domain: fusions360.com
      Template:
        Count: 2
PeerOrgs:
    - Name: PeerOrg1
      Domain: org1.fusions361.com
      Template:
        Count: 2
      Users:
        Count: 1
    - Name: PeerOrg2
      Domain: org2.fusions362.com
      Template:
        Count: 3
      Users:
        Count: 1
