version: '2' 
services:
  caOrg2:
    image: hyperledger/fabric-ca
    container_name: caOrg2
    hostname: caOrg2
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=caOrg2
      - FABRIC_CA_PRIVATEKEY=180ba90acc8a33cee7cb5487fa5d49389a266bb78c9625efc691329a509fe395_sk
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.fusions361.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/FABRIC_CA_PRIVATEKEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.fusions362.com/ca/:/etc/hyperledger/fabric-ca-server-config
    ports:
      - 7054:7054
    extra_hosts:
      - "zookeeper1:52.183.75.10"
      - "zookeeper2:52.175.231.85"
      - "zookeeper3:52.183.28.189"
      - "zookeeper4:52.175.216.219"
      - "zookeeper5:13.66.221.48"
      - "kafka1:52.183.75.10"
      - "kafka2:52.175.231.85"
      - "kafka3:52.183.28.189"
      - "kafka4:52.175.216.219"
      - "kafka5:13.66.221.48"
      - "ca1:52.183.75.10"
      - "ca2:52.175.231.85"
      - "orderer0.fusions360.com:52.183.28.189"
      - "orderer1.fusions360.com:52.175.216.219"
      - "couchdbPeer0Org1:13.66.221.48"
      - "couchdbPeer0Org2:52.183.75.10"
      - "peer0.org1.fusions361.com:52.175.231.85"
      - "peer0.org2.fusions362.com:52.183.28.189"
      - "cliOrg1:52.175.216.219"
      - "cliOrg2:13.66.221.48"